"""
micropy.py — IDE stubs for the micropy language.

Add this to the top of any .mpy file to suppress linter warnings:

    from micropy import *

This file is NOT compiled by micropy — it exists only to make Python
type checkers (Pylance, Pyright, mypy, etc.) aware of micropy's built-in
types and functions. The compiler silently skips `import micropy` and
`from micropy import *`.
"""

from typing import Any, Callable, TypeVar, Generic

_T = TypeVar("_T")

# ---------------------------------------------------------------------------
# Primitive type aliases  (used in annotations, e.g. x: ptr[int])
# ---------------------------------------------------------------------------
void    = None
byte    = int
cstr    = Any
i8  = i16  = i32  = i64  = int
u8  = u16  = u32  = u64  = int
f32 = f64  = float

class ptr(Generic[_T]):    ...
class array(Generic[_T]):  ...  # array[T, N]
class vec(Generic[_T]):    ...  # vec[T, N]
class func(Generic[_T]):   ...  # func[Ret, Arg1, ...]
class const(Generic[_T]):  ...
class volatile(Generic[_T]): ...
class static(Generic[_T]): ...
class thread_local(Generic[_T]): ...
class bitfield(Generic[_T]): ...  # bitfield[T, N]
class Result(Generic[_T]): ...
class typed_list(Generic[_T]): ...

# Concurrency handles
arena      = Any
file       = Any
thread     = Any
mutex      = Any
cond       = Any
channel    = Any
threadpool = Any

# Runtime value wrapper (internal)
MpVal      = Any
MpStr      = Any
MpList     = Any
MpDict     = Any
MpArena    = Any

# ---------------------------------------------------------------------------
# Decorators
# ---------------------------------------------------------------------------
def test(fn: _T) -> _T:          return fn
def inline(fn: _T) -> _T:        return fn
def noinline(fn: _T) -> _T:      return fn
def extern(fn: _T) -> _T:        return fn
def export(fn: _T) -> _T:        return fn
def noreturn(fn: _T) -> _T:      return fn
def cold(fn: _T) -> _T:          return fn
def hot(fn: _T) -> _T:           return fn
def simd(fn: _T) -> _T:          return fn
def packed(cls: _T) -> _T:       return cls
def union(cls: _T) -> _T:        return cls
def align(n: int) -> Callable:   return lambda x: x
def generic(**kw) -> Callable:   return lambda x: x
def trait(cls: _T) -> _T:        return cls
def impl(*args) -> Callable:     return lambda x: x
def platform(*args) -> Callable: return lambda x: x

# ---------------------------------------------------------------------------
# List / dict
# ---------------------------------------------------------------------------
def list_new() -> Any: ...
def list_free(l: Any) -> None: ...
def list_get(l: Any, i: int) -> Any: ...
def list_set(l: Any, i: int, v: Any) -> None: ...
def list_len(l: Any) -> int: ...
def list_append(l: Any, v: Any) -> None: ...
def list_pop(l: Any) -> Any: ...

def dict_new() -> Any: ...
def dict_free(d: Any) -> None: ...
def dict_get(d: Any, key: Any) -> Any: ...
def dict_set(d: Any, key: Any, val: Any) -> None: ...
def dict_len(d: Any) -> int: ...
def dict_has(d: Any, key: Any) -> bool: ...

# ---------------------------------------------------------------------------
# Strings
# ---------------------------------------------------------------------------
def str_new(s: str) -> Any: ...
def str_free(s: Any) -> None: ...
def str_concat(a: Any, b: Any) -> Any: ...
def str_len(s: Any) -> int: ...
def str_eq(a: Any, b: Any) -> bool: ...
def str_from_int(n: int) -> Any: ...
def str_from_float(f: float) -> Any: ...
def str_upper(s: Any) -> Any: ...
def str_lower(s: Any) -> Any: ...
def str_slice(s: Any, start: int, end: int) -> Any: ...
def str_find(s: Any, sub: Any) -> int: ...
def str_contains(s: Any, sub: Any) -> bool: ...
def str_starts_with(s: Any, prefix: Any) -> bool: ...
def str_ends_with(s: Any, suffix: Any) -> bool: ...
def str_repeat(s: Any, n: int) -> Any: ...
def str_strip(s: Any) -> Any: ...
def str_lstrip(s: Any) -> Any: ...
def str_rstrip(s: Any) -> Any: ...
def str_split(s: Any, sep: Any) -> Any: ...
def str_format(fmt: str, *args: Any) -> Any: ...

# ---------------------------------------------------------------------------
# Memory / pointers
# ---------------------------------------------------------------------------
def alloc(n: int) -> Any: ...
def free(p: Any) -> None: ...
def addr_of(x: Any) -> Any: ...
def deref(p: Any) -> Any: ...
def sizeof(t: Any) -> int: ...
def cast(p: Any, t: Any) -> Any: ...
def cast_int(x: Any) -> int: ...
def cast_float(x: Any) -> float: ...
def cast_byte(x: Any) -> int: ...

# ---------------------------------------------------------------------------
# Arena
# ---------------------------------------------------------------------------
def arena_new() -> Any: ...
def arena_free(a: Any) -> None: ...
def arena_list_new(a: Any) -> Any: ...
def arena_str_new(a: Any, s: str) -> Any: ...

# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------
def Ok(val: Any) -> Any: ...
def Err(msg: str) -> Any: ...
def is_ok(r: Any) -> bool: ...
def is_err(r: Any) -> bool: ...
def unwrap(r: Any) -> Any: ...
def err_msg(r: Any) -> str: ...
def try_unwrap(r: Any) -> Any: ...

# ---------------------------------------------------------------------------
# Defer
# ---------------------------------------------------------------------------
def defer(call: Any) -> None: ...

# ---------------------------------------------------------------------------
# Math / stdlib helpers
# ---------------------------------------------------------------------------
def as_int(v: Any) -> int: ...
def as_float(v: Any) -> float: ...
def sort(arr: Any, cmp: Any) -> None: ...

# ---------------------------------------------------------------------------
# Random
# ---------------------------------------------------------------------------
def rand_seed(n: int) -> None: ...
def rand_int(lo: int, hi: int) -> int: ...
def rand_float() -> float: ...

# ---------------------------------------------------------------------------
# Time
# ---------------------------------------------------------------------------
import time as _time
def time_now() -> int: return int(_time.time())
def time_ms() -> int:  return int(_time.time() * 1000)

# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------
def getenv(key: str) -> Any: ...

# ---------------------------------------------------------------------------
# Inline C
# ---------------------------------------------------------------------------
def c_include(header: str) -> None: ...
def c_code(code: str) -> None: ...

# ---------------------------------------------------------------------------
# Concurrency
# ---------------------------------------------------------------------------
def mutex_new() -> Any: ...
def mutex_lock(m: Any) -> None: ...
def mutex_unlock(m: Any) -> None: ...
def mutex_free(m: Any) -> None: ...

def cond_new() -> Any: ...
def cond_wait(c: Any, m: Any) -> None: ...
def cond_signal(c: Any) -> None: ...
def cond_broadcast(c: Any) -> None: ...
def cond_free(c: Any) -> None: ...

def thread_spawn(fn: Any, *args: Any) -> Any: ...
def thread_join(t: Any) -> None: ...

def channel_new(cap: int) -> Any: ...
def channel_send(ch: Any, val: Any) -> None: ...
def channel_recv(ch: Any, out: Any) -> None: ...
def channel_free(ch: Any) -> None: ...

def threadpool_new(n: int) -> Any: ...
def threadpool_submit(pool: Any, fn: Any, arg: Any) -> None: ...
def threadpool_wait(pool: Any) -> None: ...
def threadpool_free(pool: Any) -> None: ...

# ---------------------------------------------------------------------------
# Hot-reloading
# ---------------------------------------------------------------------------
def hotreload_open(path: str) -> Any: ...
def hotreload_sym(lib: Any, name: str) -> Any: ...
def hotreload_close(lib: Any) -> None: ...

# ---------------------------------------------------------------------------
# Variadic helpers (map to C va_list macros)
# ---------------------------------------------------------------------------
va_list = Any
def va_start(ap: Any, last: Any) -> None: ...
def va_end(ap: Any) -> None: ...
def va_arg(ap: Any, t: Any) -> Any: ...

# ---------------------------------------------------------------------------
# Testing
# ---------------------------------------------------------------------------
def test_assert(cond: bool, msg: str = "") -> None: ...

# ---------------------------------------------------------------------------
# Common C stdlib functions (used directly in micropy)
# ---------------------------------------------------------------------------
def printf(fmt: str, *args: Any) -> int:
    import sys, re
    # Normalise C-specific length modifiers (%lld → %d, %zu → %d, etc.)
    py_fmt = re.sub(r'%([-+0-9.*]*)(?:ll|l|z|h|hh)([diouxX])', r'%\1\2', fmt)
    try:    out = py_fmt % args
    except: out = fmt
    sys.stdout.write(out)
    return len(out)
def fprintf(stream: Any, fmt: str, *args: Any) -> int: ...
def sprintf(buf: Any, fmt: str, *args: Any) -> int: ...
def snprintf(buf: Any, n: int, fmt: str, *args: Any) -> int: ...
def vprintf(fmt: str, ap: Any) -> int: ...
def vsnprintf(buf: Any, n: int, fmt: str, ap: Any) -> int: ...
def scanf(fmt: str, *args: Any) -> int: ...
def fopen(path: str, mode: str) -> Any: ...
def fclose(f: Any) -> int: ...
def fread(buf: Any, size: int, n: int, f: Any) -> int: ...
def fwrite(buf: Any, size: int, n: int, f: Any) -> int: ...
def fgets(buf: Any, n: int, f: Any) -> Any: ...
def fputs(s: str, f: Any) -> int: ...
def feof(f: Any) -> bool: ...
def malloc(n: int) -> Any: ...
def calloc(n: int, size: int) -> Any: ...
def realloc(p: Any, n: int) -> Any: ...
def abort() -> None: ...
def memcpy(dst: Any, src: Any, n: int) -> Any: ...
def memset(p: Any, v: int, n: int) -> Any: ...
def memmove(dst: Any, src: Any, n: int) -> Any: ...
def memcmp(a: Any, b: Any, n: int) -> int: ...
def strlen(s: Any) -> int: ...
def strcmp(a: Any, b: Any) -> int: ...
def strncmp(a: Any, b: Any, n: int) -> int: ...
def strcpy(dst: Any, src: Any) -> Any: ...
def strncpy(dst: Any, src: Any, n: int) -> Any: ...
def strdup(s: Any) -> Any: ...
def atoi(s: Any) -> int: ...
def atof(s: Any) -> float: ...
def sleep(n: int) -> None: ...